// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOOze5RDHLmQ9Y48Yno-mOeeldrGilfmw',
    appId: '1:3760854491:web:2a2e3f74a18453410983fe',
    messagingSenderId: '3760854491',
    projectId: 'aplicacion-3-jordychoez',
    authDomain: 'aplicacion-3-jordychoez.firebaseapp.com',
    storageBucket: 'aplicacion-3-jordychoez.appspot.com',
    measurementId: 'G-CST8FD6EF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDodpwGyrNa8O8Ck0Lfg4yGAXONNhLtaxM',
    appId: '1:3760854491:android:99adf676a4f3401e0983fe',
    messagingSenderId: '3760854491',
    projectId: 'aplicacion-3-jordychoez',
    storageBucket: 'aplicacion-3-jordychoez.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBue6-ivmeDko_AzYM-ZQyXcm3fN_RAgKA',
    appId: '1:3760854491:ios:e1d5822a8642390a0983fe',
    messagingSenderId: '3760854491',
    projectId: 'aplicacion-3-jordychoez',
    storageBucket: 'aplicacion-3-jordychoez.appspot.com',
    iosBundleId: 'com.example.aplicacion3Jordychoez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBue6-ivmeDko_AzYM-ZQyXcm3fN_RAgKA',
    appId: '1:3760854491:ios:e1d5822a8642390a0983fe',
    messagingSenderId: '3760854491',
    projectId: 'aplicacion-3-jordychoez',
    storageBucket: 'aplicacion-3-jordychoez.appspot.com',
    iosBundleId: 'com.example.aplicacion3Jordychoez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOOze5RDHLmQ9Y48Yno-mOeeldrGilfmw',
    appId: '1:3760854491:web:c0b9dcffacfae7470983fe',
    messagingSenderId: '3760854491',
    projectId: 'aplicacion-3-jordychoez',
    authDomain: 'aplicacion-3-jordychoez.firebaseapp.com',
    storageBucket: 'aplicacion-3-jordychoez.appspot.com',
    measurementId: 'G-6VKTCL2TBG',
  );
}
